# Generated by Django 4.1 on 2022-08-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='star_rating',
            field=models.IntegerField(default=1),
        ),
    ]
