# Generated by Django 4.1 on 2022-08-27 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_star_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_day', '-id']},
        ),
    ]
