# Generated by Django 4.1.3 on 2022-12-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_tag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_details',
            field=models.TextField(blank=True),
        ),
    ]
